#pragma once

namespace nino
{
/*************************** CONTROLLER(CHANGE) ****************************/

#define CONTROLLER_UP				XINPUT_GAMEPAD_DPAD_UP
#define CONTROLLER_DOWN				XINPUT_GAMEPAD_DPAD_DOWN
#define CONTROLLER_LEFT				XINPUT_GAMEPAD_DPAD_LEFT
#define CONTROLLER_RIGHT			XINPUT_GAMEPAD_DPAD_RIGHT
#define CONTROLLER_START			XINPUT_GAMEPAD_START
#define CONTROLLER_BACK				XINPUT_GAMEPAD_BACK
#define CONTROLLER_LEFT_THUMB		XINPUT_GAMEPAD_LEFT_THUMB
#define CONTROLLER_RIGHT_THUMB		XINPUT_GAMEPAD_RIGHT_THUMB
#define CONTROLLER_LEFT_SHOULDER	XINPUT_GAMEPAD_LEFT_SHOULDER
#define CONTROLLER_RIGHT_SHOULDER	XINPUT_GAMEPAD_RIGHT_SHOULDER
#define CONTROLLER_A				XINPUT_GAMEPAD_A
#define CONTROLLER_B				XINPUT_GAMEPAD_B
#define CONTROLLER_X				XINPUT_GAMEPAD_X
#define CONTROLLER_Y				XINPUT_GAMEPAD_Y

/*******************************************************************/
}