#pragma once

/*************************** CONTROLLER(CHANGE) ****************************/

#define CONTROLLER_UP				XINPUT_GAMEPAD_DPAD_UP
#define CONTROLLER_DOWN				XINPUT_GAMEPAD_DPAD_DOWN
#define CONTROLLER_LEFT				XINPUT_GAMEPAD_DPAD_LEFT
#define CONTROLLER_RIGHT			XINPUT_GAMEPAD_DPAD_RIGHT
#define CONTROLLER_START			XINPUT_GAMEPAD_START
#define CONTROLLER_BACK				XINPUT_GAMEPAD_BACK
#define CONTROLLER_LEFT_THUMB		XINPUT_GAMEPAD_LEFT_THUMB
#define CONTROLLER_RIGHT_THUMB		XINPUT_GAMEPAD_RIGHT_THUMB
#define CONTROLLER_LEFT_SHOULDER	XINPUT_GAMEPAD_LEFT_SHOULDER
#define CONTROLLER_RIGHT_SHOULDER	XINPUT_GAMEPAD_RIGHT_SHOULDER
#define CONTROLLER_A				XINPUT_GAMEPAD_A
#define CONTROLLER_B				XINPUT_GAMEPAD_B
#define CONTROLLER_X				XINPUT_GAMEPAD_X
#define CONTROLLER_Y				XINPUT_GAMEPAD_Y

/*******************************************************************/

namespace nino
{
	enum KeyCode
	{
		KEY_BACK = VK_BACK,
		KEY_TAB = VK_TAB,
		KEY_CLEAR = VK_CLEAR,
		KEY_RETURN = VK_RETURN,
		KEY_SHIFT = VK_SHIFT,
		KEY_CONTROL = VK_CONTROL,
		KEY_ALT = VK_MENU,
		KEY_PAUSE = VK_PAUSE,
		KEY_CAPITAL = VK_CAPITAL,
		KEY_ESCAPE = VK_ESCAPE,
		KEY_SPACE = VK_SPACE,
		KEY_PRIOR = VK_PRIOR,
		KEY_NEXT = VK_NEXT,
		KEY_END = VK_END,
		KEY_HOME = VK_HOME,
		KEY_LEFT = VK_LEFT,
		KEY_UP = VK_UP,
		KEY_RIGHT = VK_RIGHT,
		KEY_DOWN = VK_DOWN,
		KEY_PRINT = VK_PRINT,
		KEY_SNAPSHOT = VK_SNAPSHOT,
		KEY_INSERT = VK_INSERT,
		KEY_DELETE = VK_DELETE,
		KEY_LWIN = VK_LWIN,
		KEY_RWIN = VK_RWIN,
		KEY_NUMPAD0 = VK_NUMPAD0,
		KEY_NUMPAD1 = VK_NUMPAD1,
		KEY_NUMPAD2 = VK_NUMPAD2,
		KEY_NUMPAD3 = VK_NUMPAD3,
		KEY_NUMPAD4 = VK_NUMPAD4,
		KEY_NUMPAD5 = VK_NUMPAD5,
		KEY_NUMPAD6 = VK_NUMPAD6,
		KEY_NUMPAD7 = VK_NUMPAD7,
		KEY_NUMPAD8 = VK_NUMPAD8,
		KEY_NUMPAD9 = VK_NUMPAD9,
		KEY_MULTIPLY = VK_MULTIPLY,
		KEY_ADD = VK_ADD,
		KEY_SEPARATOR = VK_SEPARATOR,
		KEY_SUBTRACT = VK_SUBTRACT,
		KEY_DECIMAL = VK_DECIMAL,
		KEY_DIVIDE = VK_DIVIDE,
		KEY_F1 = VK_F1,
		KEY_F2 = VK_F2,
		KEY_F3 = VK_F3,
		KEY_F4 = VK_F4,
		KEY_F5 = VK_F5,
		KEY_F6 = VK_F6,
		KEY_F7 = VK_F7,
		KEY_F8 = VK_F8,
		KEY_F9 = VK_F9,
		KEY_F10 = VK_F10,
		KEY_F11 = VK_F11,
		KEY_F12 = VK_F12,
		KEY_NUMLOCK = VK_NUMLOCK,
		KEY_SCROLL = VK_SCROLL,
		KEY_LSHIFT = VK_LSHIFT,
		KEY_RSHIFT = VK_RSHIFT,
		KEY_LCONTROL = VK_LCONTROL,
		KEY_RCONTROL = VK_RCONTROL,
	};

	enum MouseCode
	{
		MOUSE_LEFT = VK_LBUTTON,
		MOUSE_RIGHT = VK_RBUTTON,
		MOUSE_WHEEL = VK_MBUTTON,
		MOUSE_EXTRA1 = VK_XBUTTON1,
		MOUSE_EXTRA2 = VK_XBUTTON2,
	};

	enum JoystickBinding
	{

	};
}